### ISSUE TITLE
crash with ImageUtils

### ISSUE THREAD

**Issue by santhoshsachindran** [doublesp/Coherence#101]
This happened, exiting out of the app, seems like Glide is referencing something in the app to load an image.

`11-30 16:35:17.477 2108-2108/com.doublesp.coherence E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.doublesp.coherence, PID: 2108
                                                                      java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
                                                                          at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:134)
                                                                          at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:102)
                                                                          at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:87)
                                                                          at com.bumptech.glide.Glide.with(Glide.java:629)
                                                                          at com.doublesp.coherence.utils.ImageUtils.rotateImage(ImageUtils.java:20)
                                                                          at com.doublesp.coherence.utils.ImageUtils$1.run(ImageUtils.java:35)
                                                                          at android.os.Handler.handleCallback(Handler.java:746)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)`

**Comment by pinyaoting** [comment]
please help with investigation this crash when available, thanks

**Comment by pinyaoting** [comment]
I figured it out, will submit a PR.
