### ISSUE TITLE
Crash with reverse recipe search.

### ISSUE THREAD

**Issue by santhoshsachindran** [doublesp/Coherence#96]
11-29 23:47:13.012 17198-17198/com.doublesp.coherence E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.doublesp.coherence, PID: 17198
                                                                        java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                            at java.util.ArrayList.get(ArrayList.java:308)
                                                                            at com.doublesp.coherence.datastore.DataStore.getGoalAtPos(DataStore.java:196)
                                                                            at com.doublesp.coherence.interactors.RecipeV2Interactor.getGoalAtPos(RecipeV2Interactor.java:86)
                                                                            at com.doublesp.coherence.actions.GoalActionHandler.onPreviewButtonClick(GoalActionHandler.java:44)
                                                                            at com.doublesp.coherence.databinding.ItemGoalBinding._internalCallbackOnClick(ItemGoalBinding.java:202)
                                                                            at android.databinding.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
                                                                            at android.view.View.performClick(View.java:5201)
                                                                            at android.view.View$PerformClick.run(View.java:21163)
                                                                            at android.os.Handler.handleCallback(Handler.java:746)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by pinyaoting** [comment]
not reproducible right now, let's discuss tonight.

**Comment by pinyaoting** [comment]
please help with investigation this crash when available, thanks
